"""Rename column on comment_likes table

Revision ID: cb87215fdf96
Revises: 9d83b2594700
Create Date: 2023-05-25 20:10:08.423082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb87215fdf96'
down_revision = '9d83b2594700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_likes_tweet_id_fkey', 'comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_likes', 'comments', ['comment_id'], ['id'])
    op.drop_column('comment_likes', 'tweet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.create_foreign_key('comment_likes_tweet_id_fkey', 'comment_likes', 'comments', ['tweet_id'], ['id'])
    op.drop_column('comment_likes', 'comment_id')
    # ### end Alembic commands ###
